# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/joe/coding/projects/crypto

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/joe/coding/projects/crypto

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/coding/projects/crypto/CMakeFiles /home/joe/coding/projects/crypto//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/joe/coding/projects/crypto/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named crypto

# Build rule for target.
crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 crypto
.PHONY : crypto

# fast build rule for target.
crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/build
.PHONY : crypto/fast

#=============================================================================
# Target rules for targets named fetch

# Build rule for target.
fetch: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fetch
.PHONY : fetch

# fast build rule for target.
fetch/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fetch.dir/build.make CMakeFiles/fetch.dir/build
.PHONY : fetch/fast

#=============================================================================
# Target rules for targets named build_libzed

# Build rule for target.
build_libzed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_libzed
.PHONY : build_libzed

# fast build rule for target.
build_libzed/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_libzed.dir/build.make CMakeFiles/build_libzed.dir/build
.PHONY : build_libzed/fast

#=============================================================================
# Target rules for targets named install_libzed

# Build rule for target.
install_libzed: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 install_libzed
.PHONY : install_libzed

# fast build rule for target.
install_libzed/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/install_libzed.dir/build.make CMakeFiles/install_libzed.dir/build
.PHONY : install_libzed/fast

#=============================================================================
# Target rules for targets named clean_crypto

# Build rule for target.
clean_crypto: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean_crypto
.PHONY : clean_crypto

# fast build rule for target.
clean_crypto/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/clean_crypto.dir/build.make CMakeFiles/clean_crypto.dir/build
.PHONY : clean_crypto/fast

#=============================================================================
# Target rules for targets named count_files

# Build rule for target.
count_files: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 count_files
.PHONY : count_files

# fast build rule for target.
count_files/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/count_files.dir/build.make CMakeFiles/count_files.dir/build
.PHONY : count_files/fast

#=============================================================================
# Target rules for targets named build_tests

# Build rule for target.
build_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_tests
.PHONY : build_tests

# fast build rule for target.
build_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_tests.dir/build.make CMakeFiles/build_tests.dir/build
.PHONY : build_tests/fast

#=============================================================================
# Target rules for targets named run_tests

# Build rule for target.
run_tests: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 run_tests
.PHONY : run_tests

# fast build rule for target.
run_tests/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/run_tests.dir/build.make CMakeFiles/run_tests.dir/build
.PHONY : run_tests/fast

#=============================================================================
# Target rules for targets named build_tools

# Build rule for target.
build_tools: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 build_tools
.PHONY : build_tools

# fast build rule for target.
build_tools/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/build_tools.dir/build.make CMakeFiles/build_tools.dir/build
.PHONY : build_tools/fast

#=============================================================================
# Target rules for targets named wikiAnalyzer

# Build rule for target.
wikiAnalyzer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 wikiAnalyzer
.PHONY : wikiAnalyzer

# fast build rule for target.
wikiAnalyzer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/build
.PHONY : wikiAnalyzer/fast

#=============================================================================
# Target rules for targets named randomAnalyzer

# Build rule for target.
randomAnalyzer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 randomAnalyzer
.PHONY : randomAnalyzer

# fast build rule for target.
randomAnalyzer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/build
.PHONY : randomAnalyzer/fast

#=============================================================================
# Target rules for targets named caesarAnalyzer

# Build rule for target.
caesarAnalyzer: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 caesarAnalyzer
.PHONY : caesarAnalyzer

# fast build rule for target.
caesarAnalyzer/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/build
.PHONY : caesarAnalyzer/fast

crypto.o: crypto.cpp.o
.PHONY : crypto.o

# target to build an object file
crypto.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/crypto.cpp.o
.PHONY : crypto.cpp.o

crypto.i: crypto.cpp.i
.PHONY : crypto.i

# target to preprocess a source file
crypto.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/crypto.cpp.i
.PHONY : crypto.cpp.i

crypto.s: crypto.cpp.s
.PHONY : crypto.s

# target to generate assembly for a file
crypto.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/crypto.cpp.s
.PHONY : crypto.cpp.s

src/ciphers/caesar.o: src/ciphers/caesar.cpp.o
.PHONY : src/ciphers/caesar.o

# target to build an object file
src/ciphers/caesar.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/ciphers/caesar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/ciphers/caesar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/ciphers/caesar.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/ciphers/caesar.cpp.o
.PHONY : src/ciphers/caesar.cpp.o

src/ciphers/caesar.i: src/ciphers/caesar.cpp.i
.PHONY : src/ciphers/caesar.i

# target to preprocess a source file
src/ciphers/caesar.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/ciphers/caesar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/ciphers/caesar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/ciphers/caesar.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/ciphers/caesar.cpp.i
.PHONY : src/ciphers/caesar.cpp.i

src/ciphers/caesar.s: src/ciphers/caesar.cpp.s
.PHONY : src/ciphers/caesar.s

# target to generate assembly for a file
src/ciphers/caesar.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/ciphers/caesar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/ciphers/caesar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/ciphers/caesar.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/ciphers/caesar.cpp.s
.PHONY : src/ciphers/caesar.cpp.s

src/ciphers/substitution.o: src/ciphers/substitution.cpp.o
.PHONY : src/ciphers/substitution.o

# target to build an object file
src/ciphers/substitution.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/ciphers/substitution.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/ciphers/substitution.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/ciphers/substitution.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/ciphers/substitution.cpp.o
.PHONY : src/ciphers/substitution.cpp.o

src/ciphers/substitution.i: src/ciphers/substitution.cpp.i
.PHONY : src/ciphers/substitution.i

# target to preprocess a source file
src/ciphers/substitution.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/ciphers/substitution.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/ciphers/substitution.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/ciphers/substitution.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/ciphers/substitution.cpp.i
.PHONY : src/ciphers/substitution.cpp.i

src/ciphers/substitution.s: src/ciphers/substitution.cpp.s
.PHONY : src/ciphers/substitution.s

# target to generate assembly for a file
src/ciphers/substitution.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/ciphers/substitution.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/ciphers/substitution.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/ciphers/substitution.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/ciphers/substitution.cpp.s
.PHONY : src/ciphers/substitution.cpp.s

src/helpers/dictionary.o: src/helpers/dictionary.cpp.o
.PHONY : src/helpers/dictionary.o

# target to build an object file
src/helpers/dictionary.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/helpers/dictionary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/helpers/dictionary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/helpers/dictionary.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/helpers/dictionary.cpp.o
.PHONY : src/helpers/dictionary.cpp.o

src/helpers/dictionary.i: src/helpers/dictionary.cpp.i
.PHONY : src/helpers/dictionary.i

# target to preprocess a source file
src/helpers/dictionary.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/helpers/dictionary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/helpers/dictionary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/helpers/dictionary.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/helpers/dictionary.cpp.i
.PHONY : src/helpers/dictionary.cpp.i

src/helpers/dictionary.s: src/helpers/dictionary.cpp.s
.PHONY : src/helpers/dictionary.s

# target to generate assembly for a file
src/helpers/dictionary.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/helpers/dictionary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/helpers/dictionary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/helpers/dictionary.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/helpers/dictionary.cpp.s
.PHONY : src/helpers/dictionary.cpp.s

src/helpers/parser.o: src/helpers/parser.cpp.o
.PHONY : src/helpers/parser.o

# target to build an object file
src/helpers/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/helpers/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/helpers/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/helpers/parser.cpp.o
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/helpers/parser.cpp.o
.PHONY : src/helpers/parser.cpp.o

src/helpers/parser.i: src/helpers/parser.cpp.i
.PHONY : src/helpers/parser.i

# target to preprocess a source file
src/helpers/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/helpers/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/helpers/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/helpers/parser.cpp.i
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/helpers/parser.cpp.i
.PHONY : src/helpers/parser.cpp.i

src/helpers/parser.s: src/helpers/parser.cpp.s
.PHONY : src/helpers/parser.s

# target to generate assembly for a file
src/helpers/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/crypto.dir/build.make CMakeFiles/crypto.dir/src/helpers/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/src/helpers/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/src/helpers/parser.cpp.s
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/src/helpers/parser.cpp.s
.PHONY : src/helpers/parser.cpp.s

tools/analyzer/caesarAnalyzer.o: tools/analyzer/caesarAnalyzer.cpp.o
.PHONY : tools/analyzer/caesarAnalyzer.o

# target to build an object file
tools/analyzer/caesarAnalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/tools/analyzer/caesarAnalyzer.cpp.o
.PHONY : tools/analyzer/caesarAnalyzer.cpp.o

tools/analyzer/caesarAnalyzer.i: tools/analyzer/caesarAnalyzer.cpp.i
.PHONY : tools/analyzer/caesarAnalyzer.i

# target to preprocess a source file
tools/analyzer/caesarAnalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/tools/analyzer/caesarAnalyzer.cpp.i
.PHONY : tools/analyzer/caesarAnalyzer.cpp.i

tools/analyzer/caesarAnalyzer.s: tools/analyzer/caesarAnalyzer.cpp.s
.PHONY : tools/analyzer/caesarAnalyzer.s

# target to generate assembly for a file
tools/analyzer/caesarAnalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/caesarAnalyzer.dir/build.make CMakeFiles/caesarAnalyzer.dir/tools/analyzer/caesarAnalyzer.cpp.s
.PHONY : tools/analyzer/caesarAnalyzer.cpp.s

tools/analyzer/randomAnalyzer.o: tools/analyzer/randomAnalyzer.cpp.o
.PHONY : tools/analyzer/randomAnalyzer.o

# target to build an object file
tools/analyzer/randomAnalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/tools/analyzer/randomAnalyzer.cpp.o
.PHONY : tools/analyzer/randomAnalyzer.cpp.o

tools/analyzer/randomAnalyzer.i: tools/analyzer/randomAnalyzer.cpp.i
.PHONY : tools/analyzer/randomAnalyzer.i

# target to preprocess a source file
tools/analyzer/randomAnalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/tools/analyzer/randomAnalyzer.cpp.i
.PHONY : tools/analyzer/randomAnalyzer.cpp.i

tools/analyzer/randomAnalyzer.s: tools/analyzer/randomAnalyzer.cpp.s
.PHONY : tools/analyzer/randomAnalyzer.s

# target to generate assembly for a file
tools/analyzer/randomAnalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/randomAnalyzer.dir/build.make CMakeFiles/randomAnalyzer.dir/tools/analyzer/randomAnalyzer.cpp.s
.PHONY : tools/analyzer/randomAnalyzer.cpp.s

tools/analyzer/wikiAnalyzer.o: tools/analyzer/wikiAnalyzer.cpp.o
.PHONY : tools/analyzer/wikiAnalyzer.o

# target to build an object file
tools/analyzer/wikiAnalyzer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/tools/analyzer/wikiAnalyzer.cpp.o
.PHONY : tools/analyzer/wikiAnalyzer.cpp.o

tools/analyzer/wikiAnalyzer.i: tools/analyzer/wikiAnalyzer.cpp.i
.PHONY : tools/analyzer/wikiAnalyzer.i

# target to preprocess a source file
tools/analyzer/wikiAnalyzer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/tools/analyzer/wikiAnalyzer.cpp.i
.PHONY : tools/analyzer/wikiAnalyzer.cpp.i

tools/analyzer/wikiAnalyzer.s: tools/analyzer/wikiAnalyzer.cpp.s
.PHONY : tools/analyzer/wikiAnalyzer.s

# target to generate assembly for a file
tools/analyzer/wikiAnalyzer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/wikiAnalyzer.dir/build.make CMakeFiles/wikiAnalyzer.dir/tools/analyzer/wikiAnalyzer.cpp.s
.PHONY : tools/analyzer/wikiAnalyzer.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... build_libzed"
	@echo "... build_tests"
	@echo "... build_tools"
	@echo "... clean_crypto"
	@echo "... count_files"
	@echo "... fetch"
	@echo "... install_libzed"
	@echo "... run_tests"
	@echo "... caesarAnalyzer"
	@echo "... crypto"
	@echo "... randomAnalyzer"
	@echo "... wikiAnalyzer"
	@echo "... crypto.o"
	@echo "... crypto.i"
	@echo "... crypto.s"
	@echo "... src/ciphers/caesar.o"
	@echo "... src/ciphers/caesar.i"
	@echo "... src/ciphers/caesar.s"
	@echo "... src/ciphers/substitution.o"
	@echo "... src/ciphers/substitution.i"
	@echo "... src/ciphers/substitution.s"
	@echo "... src/helpers/dictionary.o"
	@echo "... src/helpers/dictionary.i"
	@echo "... src/helpers/dictionary.s"
	@echo "... src/helpers/parser.o"
	@echo "... src/helpers/parser.i"
	@echo "... src/helpers/parser.s"
	@echo "... tools/analyzer/caesarAnalyzer.o"
	@echo "... tools/analyzer/caesarAnalyzer.i"
	@echo "... tools/analyzer/caesarAnalyzer.s"
	@echo "... tools/analyzer/randomAnalyzer.o"
	@echo "... tools/analyzer/randomAnalyzer.i"
	@echo "... tools/analyzer/randomAnalyzer.s"
	@echo "... tools/analyzer/wikiAnalyzer.o"
	@echo "... tools/analyzer/wikiAnalyzer.i"
	@echo "... tools/analyzer/wikiAnalyzer.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

